stages:
    - test

variables:
    # SRCDIR is still used for module-unaware building, for Go 1.9, 1.10, and GopherJS
    SRCDIR: /go/src/github.com/go-kivik/kivik
    GO111MODULE: "on"

vendor:
    image: golang:1.13
    script:
        - go mod vendor
    artifacts:
        - vendor

.test: &test_template
    stage: test
    services:
        - name: apache/couchdb:2.3.1
          alias: couch23
    variables:
        COUCHDB_USER: admin
        COUCHDB_PASSWORD: abc123
        KIVIK_TEST_DSN_COUCH23: http://admin:abc123@couch23:5984/
    before_script:
        - ./script/complete_couch2.sh ${KIVIK_TEST_DSN_COUCH23}
    script:
        - go mod download
        - ./script/test_version.sh
        - go test -race -tags=livetest ./...

.nomod: &nomod_template
    <<: *test_template
    script:
        - mkdir -p /go/src
        - ln -s /builds /go/src/github.com
        - cd ${SRCDIR}
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        - dep ensure && dep status
        - ./script/test_version.sh
        - go test -race -tags=livetest ./...

lint:
    stage: test
    image: golang:1.13
    services: []
    before_script:
        - ''
    script:
        - go mod download
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.22.2
        - golangci-lint run ./...

coverage:
    stage: test
    image: golang:1.13
    services: []
    before_script:
        - ''
    script:
        - go mod download
        - ./script/coverage.sh


go-1.9:
    <<: *nomod_template
    image: golang:1.9

go-1.10:
    <<: *nomod_template
    image: golang:1.10

go-1.11:
    <<: *test_template
    image: golang:1.11

go-1.12:
    <<: *test_template
    image: golang:1.12

go-1.13:
    <<: *test_template
    image: golang:1.13

gopherjs-1.12:
    <<: *nomod_template
    image: golang:1.13
    script:
        - go get golang.org/dl/go1.12.16
        - go1.12.16 download
        - mkdir -p /go/src
        - ln -s /builds /go/src/github.com
        - cd ${SRCDIR}
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        - dep ensure && dep status
        - curl -sL https://deb.nodesource.com/setup_12.x | bash -
        - apt-get update -qq && apt-get install -y nodejs
        - npm install
        - GO111MODULE=off go get -u github.com/gopherjs/gopherjs
        - npm install source-map-support
        - |
            (
                cd $GOPATH/src/github.com/gopherjs/gopherjs/node-syscall/
                npm install --global node-gyp
                node-gyp rebuild
                mkdir -p ~/.node_libraries/
                cp build/Release/syscall.node ~/.node_libraries/syscall.node
            )
        - GOPHERJS_GOROOT="$(go1.12.16 env GOROOT)" gopherjs test ./...

go-rc:
    <<: *test_template
    image: golang:rc
    allow_failure: true
