dist: trusty
sudo: required
services:
    - docker
addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide
cache:
    directories:
        - node_modules
        - $HOME/gopath/pkg

language: go

os:
    - linux
go:
    - 1.7.x
    - 1.8.x
    - 1.9.x
    - master
env:
    global:
        - KIVIK_TEST_DSN="http://admin:abc123@localhost:6000/"
        - HOMEBREW_NO_AUTO_UPDATE=1
    matrix:
        - MODE=standard
        - MODE=docker DOCKER_IMAGE=couchdb:1.6.1
        - MODE=docker DOCKER_IMAGE=klaemo/couchdb:2.0.0
        - MODE=docker DOCKER_IMAGE=apache/couchdb:2.1.0

matrix:
    fast_finish: true
    allow_failures:
        - go: master
    include:
        - os: osx
          go: 1.7.x
          env: MODE=standard
        - os: osx
          go: 1.8.x
          env: MODE=standard
        - os: osx
          go: 1.9.x
          env: MODE=standard
        - os: osx
          go: master
          env: MODE=standard
        - go: 1.9.x
          env: MODE=gopherjs DOCKER_IMAGE=apache/couchdb:2.1.0
        - go: 1.9.x
          env: MODE=linter
        - go: 1.9.x
          env: MODE=coverage

install:
    - ./travis/install.sh $MODE

script:
    - ./travis/test.sh $MODE
