dist: trusty
sudo: required
services:
    - docker

language: go

os:
    - linux

go:
    - 1.8.x
env:
    global:
        - KIVIK_TEST_DSN_COUCH16="http://admin:abc123@localhost:6000/"
        - KIVIK_TEST_DSN_COUCH20="http://admin:abc123@localhost:6001/"
    matrix:
        - MODE=standard

matrix:
    allow_failures:
        - go: master
    include:
        - go: 1.8.x
          env: MODE=gopherjs
        - go: 1.8.x
          env: MODE=linter
        - go: 1.8.x
          env: MODE=coverage

install:
    - ./travis/install.sh $MODE

script:
    - ./travis/test.sh $MODE
